<?php

/**
 * Implements hook_sms_incoming().
 */
function vozmob_envaya_sms_incoming($op, $number, $message, $options)  {
  global $user;
  if ($op != 'process') {
    return;
  }
  watchdog('vozmob_envaya', '<pre>' . check_plain(print_r($options['sms_envaya_action'], TRUE)) . '</pre>', NULL);
  $node->type = 'article';
  node_object_prepare($node);
  $node->title = $message;
  $node->uid = $user->uid;
  $node->language = LANGUAGE_NONE;
  $node->body[$node->language][0]['format'] = 'filtered_html';
  $node->body[$node->language][0]['summary'] = text_summary($message);
  $node->body[$node->language][0]['value'] = $message;
  if ($options['sms_envaya_action']->mms_parts) {
    $allowed_extensions = '3g2 3gp 3gpp amr avi bmp gif jpeg jpg m4a m4v mp3 mp4 mpeg mpg png qcelp qcp smil txt wav wbmp';
    $directory = 'public://' . gmdate('Y/m/d');
    file_prepare_directory($directory, FILE_CREATE_DIRECTORY | FILE_MODIFY_PERMISSIONS);
    foreach ($options['sms_envaya_action']->mms_parts as $mms_part) {
      if (file_get_mimetype($mms_part->filename) == 'application/octet-stream') {
        $mapping = file_default_mimetype_mapping();
        $mapping['mimetypes'] = array_flip($mapping['mimetypes']);
        $mapping['extensions'] = array_flip($mapping['extensions']);
        if (isset($mapping['mimetypes'][$mms_part->type])) {
          $_FILES['files']['name'][$mms_part->form_name] .= '.' . $mapping['extensions'][$mapping['mimetypes'][$mms_part->type]];
        }
      }
      $file = file_save_upload($mms_part->form_name, array('file_validate_extensions' => array($allowed_extensions)), $directory, FILE_EXISTS_RENAME);
      if ($file) {
        $field = preg_match('!^image/(gif|jpeg|png)$!', $file->filemime) ? 'field_image' : 'field_file';
        $node->{$field}[$node->language][] = array(
          'display' => 1,
          'fid' => $file->fid,
          'filename' => $file->filename,
          'filemime' => $file->filemime,
          'uid' => 1,
          'uri' => $file->uri,
          'status' => 1,
        );
      }
      else {
        watchdog('vozmob_envaya', 'file_save_upload() failed for %mms_part.', array('%mms_part' => print_r($mms_part, TRUE)), WATCHDOG_ERROR);
      }
    }
  }
  node_save($node);
}
